T1

diff --git a/openstack/glance/templates/glance-nanny-deployment.yaml b/openstack/glance/templates/glance-nanny-deployment.yaml
--- a/openstack/glance/templates/glance-nanny-deployment.yaml
+++ b/openstack/glance/templates/glance-nanny-deployment.yaml
@@ -43,18 +43,33 @@ spec:
         {{- end }}
         {{- include "utils.linkerd.pod_and_service_annotation" . | indent 8 }}
     spec:
-      {{ include "utils.proxysql.pod_settings" . | indent 6 }}
-{{- if .Values.glance_nanny.db_purge.enabled }}
+      initContainers:
+      - name: init-check
+        image: {{ required ".Values.global.registry is missing" .Values.global.registry }}/init-check-image:latest
+        imagePullPolicy: IfNotPresent
+        command:
+        - /bin/bash
+        - -c
+        - |
+          # Example of a check before starting the main container
+          if [ ! -f /scripts/glance-db-consistency-and-purge.sh ]; then
+            echo "Error: /scripts/glance-db-consistency-and-purge.sh not found."
+            exit 1
+          fi
+        volumeMounts:
+        - name: glance-scripts
+          mountPath: /scripts
+        {{- include "utils.proxysql.volume_mount" . | indent 8 }}
+        {{- include "utils.trust_bundle.volume_mount" . | indent 8 }}
       containers:
       - name: db-consistency-and-purge
         image: {{ required ".Values.global.registry is missing" .Values.global.registry }}/loci-glance:{{.Values.imageVersionGlanceApi | default .Values.imageVersion | default .Values.image_version | required "Please set glance.imageVersion or similar"}}
         imagePullPolicy: IfNotPresent
         command:
         - dumb-init
-        - kubernetes-entrypoint
+        - /bin/bash
+        - /scripts/glance-db-consistency-and-purge.sh
         env:
-        - name: COMMAND
-          value: "{{ if not .Values.glance_nanny.debug }}/bin/bash /scripts/glance-db-consistency-and-purge.sh{{ else }}sleep inf{{ end }}"
         - name: GLANCE_DB_PURGE_ENABLED
           value: {{ .Values.glance_nanny.db_purge.enabled | quote }}
         - name: GLANCE_DB_PURGE_OLDER_THAN
@@ -79,16 +94,10 @@ spec:
             cpu: "100m"
         volumeMounts:
         - name: glance-scripts
-          mountPath: /scripts/glance-db-consistency-and-purge.sh
-          subPath: glance-db-consistency-and-purge.sh
+          mountPath: /scripts
           readOnly: true
         - name: glance-etc
-          mountPath: /etc/glance/glance-api.conf
-          subPath: glance-api.conf
-          readOnly: true
-        - name: glance-etc
-          mountPath: /etc/glance/logging.ini
-          subPath: logging.ini
+          mountPath: /etc/glance
           readOnly: true
         - name: glance-etc-confd
           mountPath: /etc/glance/glance.conf.d
